language: ruby

dist: trusty

addons:
  postgresql: '10.4'

services:
  - postgresql

before_install:
  - echo "Installing libvips..."
  - sudo apt-get update
  - sudo apt-get install -y libvips libvips-dev
  - echo "Updating gems..."
  - gem update --system

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bin/rails test
  - bin/rails cucumber

services:
  - postgresql

bundler_args: --without production
