language: ruby

before_script:
  - psql -c 'create database booker_test;' -U postgres

script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bin/rails test
  - bin/rails cucumber
  
services:
  - postgresql

bundler_args: --without production
