language: ruby

cache:
  - bundler
  - yarn

dist: trusty

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5433

services:
  - postgresql
  - memcached
  - redis-server

before_script:
  - bin/rails db:create
  - bin/rails db:migrate RAILS_ENV=test
  - bin/rails webpacker:yarn_install
  - bin/rails webpacker:compile

script:
  - bin/rails test
  - bin/rails cucumber

bundler_args: --without production
